#!/usr/bin/env python3
"""Generate a co-author ratification worksheet for the SSc-Tier-1 evidence pass.

Part of the curation-depth pass (see docs/curation/curation_depth_pass.md). Turns the 34 `proposed`
citations + 10 reclassifications + 1 `untested` backlog row into a tick-and-correct sheet so
the co-author ratifies in minutes instead of re-opening every abstract.

For each row needing ratification it shows:
  - the exact causal claim (mechanism + participants),
  - the assigned PMID (PubMed link), its title, and **the abstract sentence that supports
    the claim** (highest gene/keyword overlap),
  - the ECO code, and
  - ⚠️ flags: review-grade evidence, a PMID shared across several rows, non-SSc context,
    or a partial entity match (the abstract does not mention all key genes),
  - checkboxes: [ ] confirm  [ ] replace (candidate pool given)  [ ] reject.

`confirmed` rows (original curation) are excluded — nothing to ratify there.

Outputs:
    curation/ratification_worksheet.md
    curation/lit_candidates/_abstracts.json   (abstract cache; re-runs offline)

Run:
    python3 scripts/build_ratification_worksheet.py
or  make ratification-worksheet

Network call (NCBI efetch) only for abstracts not already cached.
"""
from __future__ import annotations

import csv
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path
from xml.etree import ElementTree as ET

ROOT = Path(__file__).resolve().parents[1]
SSC = ROOT / "curation/ssc_curated_reactions.tsv"
CACHE = ROOT / "curation/lit_candidates/_abstracts.json"
OUT = ROOT / "curation/ratification_worksheet.md"
EFETCH = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi"
UA = "SSc-MIM-worksheet/0.1 (mailto:nathan.foulquier.pro@gmail.com)"

GENE_RE = re.compile(r"^[A-Z][A-Z0-9]{1,6}$")
EXPERIMENTAL = {"ECO:0000314", "ECO:0000270", "ECO:0000353", "ECO:0000315"}


def genes_from(*fields: str) -> list[str]:
    out: list[str] = []
    for fld in fields:
        for chunk in re.split(r";", fld or ""):
            base = chunk.split("__", 1)[0]
            if not base or base.startswith("phenotype_"):
                continue
            for tok in re.split(r"[_:]", base):
                tok = tok.strip().rstrip("p")
                if GENE_RE.match(tok) and tok not in out:
                    out.append(tok)
    return out


def fetch_abstracts(pmids: list[str]) -> dict[str, dict]:
    cache = json.loads(CACHE.read_text()) if CACHE.exists() else {}
    missing = [p for p in pmids if p and p not in cache]
    if missing:
        url = EFETCH + "?" + urllib.parse.urlencode(
            {"db": "pubmed", "id": ",".join(missing), "retmode": "xml"})
        req = urllib.request.Request(url, headers={"User-Agent": UA})
        root = ET.fromstring(urllib.request.urlopen(req, timeout=60).read())
        for art in root.findall(".//PubmedArticle"):
            pmid = art.findtext(".//PMID") or ""
            title = (art.findtext(".//ArticleTitle") or "").strip()
            ab = " ".join((t.text or "") for t in art.findall(".//Abstract/AbstractText"))
            ptypes = [pt.text for pt in art.findall(".//PublicationType")]
            cache[pmid] = {"title": title, "abstract": ab, "is_review": "Review" in ptypes}
        CACHE.write_text(json.dumps(cache, indent=2))
    return cache


def best_sentence(abstract: str, genes: list[str], mech: str) -> tuple[str, int]:
    """Return (best supporting sentence, its overlap score)."""
    sents = [s for s in re.split(r"(?<=[.!?])\s+", abstract or "") if len(s.strip()) > 25]
    kws = [w.lower() for w in re.findall(r"[a-zA-Z]{5,}", mech or "")]
    best, score = "", -1
    for s in sents:
        sl = s.lower()
        sc = sum(1 for g in genes if g.lower() in sl) * 2 + sum(1 for k in kws if k in sl)
        if sc > score:
            best, score = s.strip(), sc
    return best[:320], max(score, 0)


def main() -> None:
    rows = list(csv.DictReader(SSC.open(), delimiter="\t"))
    need = [r for r in rows if (r.get("curation_status", "") or "").strip()
            in {"proposed", "conceptual_bridge", "phenotype_aggregation", "untested"}]
    proposed = [r for r in need if r["curation_status"].strip() == "proposed"]

    pmid_uses: dict[str, int] = {}
    for r in proposed:
        pmid_uses[r["pmid"].strip()] = pmid_uses.get(r["pmid"].strip(), 0) + 1
    cache = fetch_abstracts(list(pmid_uses))

    md: list[str] = []
    md.append("# Ratification worksheet — SSc-Tier-1 evidence pass\n")
    md.append("_Auto-generated by `scripts/build_ratification_worksheet.py`. Each row was "
              "assigned by literature mining + abstract reading and is **proposed**, not yet "
              "expert-ratified. Tick `[x] confirm` to accept (sets `curation_status=confirmed`), "
              "or note a replacement/rejection. Tiered policy: review-grade `ECO:0000033` is "
              "accepted for canonical mechanisms; crosstalk needs primary/experimental — see "
              "`docs/curation/mi2cast_checklist.md`._\n")
    md.append(f"**To ratify:** {len(proposed)} proposed citations · "
              f"{sum(1 for r in need if r['curation_status'].strip() in {'conceptual_bridge','phenotype_aggregation'})} "
              f"reclassifications · {sum(1 for r in need if r['curation_status'].strip()=='untested')} untested backlog.\n")
    md.append("---\n")

    # 1) proposed citations, grouped by module
    md.append("## 1. Proposed citations — verify the snippet supports the claim\n")
    for mod in ["M1", "M2", "M3", "M4", "crosstalk"]:
        block = [r for r in proposed if r["module"].strip() == mod]
        if not block:
            continue
        md.append(f"### Module {mod}\n")
        for r in block:
            rid, pmid, eco = r["reaction_id"], r["pmid"].strip(), r["evidence_code"].strip()
            genes = genes_from(r["reactants"], r["products"], r["modifiers"])
            rec = cache.get(pmid, {})
            snippet, sent_score = best_sentence(rec.get("abstract", ""), genes, r["mechanism"])
            flags = []
            if rec.get("is_review") or eco == "ECO:0000033":
                flags.append("review-grade (ECO:0000033) — OK for canonical, upgrade to primary if preferred")
            if pmid_uses.get(pmid, 0) > 1:
                flags.append(f"PMID shared by {pmid_uses[pmid]} reactions (re-used for related edges)")
            ab_l = rec.get("abstract", "").lower()
            genes_in_ab = [g for g in genes if g.lower() in ab_l]
            # Only flag a genuinely weak fit: no gene symbol anywhere AND a low-overlap snippet
            # (abstracts often use prose names, so symbol-absence alone is not a red flag).
            if genes and not genes_in_ab and sent_score < 2:
                flags.append("weak fit — no HGNC symbol in the abstract; verify the paper uses "
                             "prose synonyms for " + ", ".join(genes[:4]))
            # SSc-context only matters for crosstalk (guidelines §7); canonical edges are general.
            if mod == "crosstalk" and "sclerod" not in ab_l and "systemic sclerosis" not in ab_l:
                flags.append("crosstalk in non-SSc context — guidelines §7 prefer an SSc-specific PMID")
            md.append(f"#### `{rid}` — {r['mechanism']}")
            md.append(f"- **Claim**: {r['reactants']} → {r['products']}"
                      + (f"  [mod: {r['modifiers']}]" if r['modifiers'].strip() else ""))
            md.append(f"- **PMID** [{pmid}](https://pubmed.ncbi.nlm.nih.gov/{pmid}/) "
                      f"· ECO `{eco}` · _{rec.get('title','(title pending)')}_")
            md.append(f"- **Supporting sentence**: {snippet or '(no abstract sentence extracted — check manually)'}")
            for f in flags:
                md.append(f"- ⚠️ {f}")
            alts = r.get("candidate_pmids", "").strip()
            md.append(f"- Alternatives if replacing: {alts or '(see curation/lit_candidates/'+rid+'.json)'}")
            md.append("- [ ] confirm  [ ] replace  [ ] reject\n")

    # 2) reclassifications
    recl = [r for r in need if r["curation_status"].strip() in {"conceptual_bridge", "phenotype_aggregation"}]
    md.append("## 2. Reclassifications — confirm these are cell-state / phenotype assertions (not molecular interactions)\n")
    for r in recl:
        md.append(f"- `{r['reaction_id']}` (**{r['curation_status'].strip()}**) — {r['mechanism']}  "
                  f"_({r['ssc_relevance']})_  [ ] confirm  [ ] convert to citation")
    md.append("")

    # 3) untested backlog
    unt = [r for r in need if r["curation_status"].strip() == "untested"]
    md.append("## 3. Untested backlog — still needs a primary citation\n")
    for r in unt:
        md.append(f"- `{r['reaction_id']}` — {r['mechanism']}  · candidate pool: "
                  f"{r.get('candidate_pmids','').strip() or '(see lit_candidates/)'}  [ ] cite  [ ] reclassify  [ ] remove")
    md.append("")

    OUT.write_text("\n".join(md))
    print(f"[worksheet] {len(proposed)} proposed + {len(recl)} reclassified + {len(unt)} untested "
          f"-> {OUT}")


if __name__ == "__main__":
    main()
