#!/usr/bin/env python3
"""Curator-inference register for the weak SSc-curated layer (H3).

Part of the v1.1 hardening sprint (see ROADMAP "v1.1 hardening sprint").

45 of the 85 SSc-curated reactions carry ECO:0000305 (curator inference) with
no primary PMID. These are the genuinely weak rows of the SSc-specific layer
(the part that differentiates this map from a Reactome re-export). Rather than
leave them implicit, this script materialises an explicit, actionable register:
one row per inference reaction, annotated with

  * validation_status   - independent computational support, if any
  * lit_search_needed    - True => co-author literature pass should target it
  * suggested_action     - concrete next step

Independent computational support is pulled, where available, from the STRING-DB
v12 crosstalk validation already in analysis/network/crosstalk_string_validation.json.

This is the review packet for the co-author / clinician sign-off (H5): it scopes
exactly which assertions need a citation and which already have one form of
independent corroboration.

Outputs:
    curation/curator_inference_register.tsv
    curation/curator_inference_register.md

Run:
    python3 scripts/build_inference_register.py
or  make inference-register
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
SSC_CURATED = ROOT / "curation/ssc_curated_reactions.tsv"
STRING_JSON = ROOT / "analysis/network/crosstalk_string_validation.json"
OUT_TSV = ROOT / "curation/curator_inference_register.tsv"
OUT_MD = ROOT / "curation/curator_inference_register.md"


def has_pmid(value: str) -> bool:
    v = (value or "").strip()
    return bool(v) and v != "-" and bool(re.search(r"\d", v))


def main() -> None:
    df = pd.read_csv(SSC_CURATED, sep="\t", dtype=str, keep_default_na=False)

    string_rows = {}
    if STRING_JSON.exists():
        string_rows = json.loads(STRING_JSON.read_text()).get("rows", {})

    # The weak layer: curator inference (ECO:0000305) AND no primary PMID.
    weak = df[(df["evidence_code"].str.strip() == "ECO:0000305") & (~df["pmid"].apply(has_pmid))].copy()

    records = []
    for _, r in weak.iterrows():
        rid = r["reaction_id"]
        s = string_rows.get(rid)
        if s is not None:
            if s.get("string_validated"):
                vstatus = (f"STRING-confirmed ({s['n_pairs_confirmed_ge_700']}/"
                           f"{s['n_pairs_tested']} pairs >=0.700, max {s['max_combined_score']})")
                lit_needed = False
                action = "independent STRING support; PMID still desirable but lower priority"
            else:
                vstatus = (f"STRING-not-confirmed (0/{s['n_pairs_tested']} pairs >=0.700, "
                           f"max {s.get('max_combined_score')})")
                lit_needed = True
                action = ("cell-state-level assertion not captured by protein-protein "
                          "STRING graph; needs targeted primary-literature citation or "
                          "explicit reclassification as a conceptual bridge")
        else:
            vstatus = "untested"
            lit_needed = True
            action = "co-author literature pass: find primary PMID or downgrade/remove"

        records.append({
            "reaction_id": rid,
            "module": r["module"],
            "type": r["type"],
            "mechanism": r["mechanism"],
            "reactants": r["reactants"],
            "products": r["products"],
            "modifiers": r["modifiers"],
            "ssc_relevance": r["ssc_relevance"],
            "evidence_code": r["evidence_code"],
            "validation_status": vstatus,
            "lit_search_needed": lit_needed,
            "suggested_action": action,
        })

    reg = pd.DataFrame(records).sort_values(["module", "reaction_id"]).reset_index(drop=True)
    reg.to_csv(OUT_TSV, sep="\t", index=False)

    n = len(reg)
    n_string_ok = int((reg["validation_status"].str.startswith("STRING-confirmed")).sum())
    n_string_no = int((reg["validation_status"].str.startswith("STRING-not")).sum())
    n_untested = int((reg["validation_status"] == "untested").sum())
    by_module = reg["module"].value_counts().to_dict()

    md = []
    md.append("# Curator-inference register (SSc-curated layer)\n")
    md.append("_Auto-generated by `scripts/build_inference_register.py` (v1.1 hardening sprint, H3)._\n")
    md.append(
        f"Of the 85 SSc-curated reactions, **{n}** carry curator inference "
        f"(`ECO:0000305`) with no primary PMID. This register scopes the literature "
        f"backlog for the co-author / clinician sign-off.\n"
    )
    md.append("## Summary\n")
    md.append("| Validation status | n |")
    md.append("|---|---|")
    md.append(f"| STRING-confirmed (independent support) | {n_string_ok} |")
    md.append(f"| STRING-not-confirmed (cell-state, needs citation) | {n_string_no} |")
    md.append(f"| Untested (needs co-author lit pass) | {n_untested} |")
    md.append(f"| **Total weak rows** | **{n}** |")
    md.append("")
    md.append("By module: " + ", ".join(f"{m} = {c}" for m, c in sorted(by_module.items())) + "\n")
    md.append(
        f"**Actionable bottom line:** {int(reg['lit_search_needed'].sum())}/{n} weak rows "
        f"need a targeted primary-literature citation (or explicit downgrade) before the "
        f"SSc-specific layer can be described as fully evidence-graded. Only "
        f"{n_string_ok} of the inference rows currently has an independent computational "
        f"corroboration (STRING-DB v12).\n"
    )
    md.append("## Full register\n")
    md.append("See `curator_inference_register.tsv`. Reaction IDs needing a lit pass:\n")
    md.append("| reaction_id | module | type | mechanism | validation_status |")
    md.append("|---|---|---|---|---|")
    for _, r in reg.iterrows():
        mech = r["mechanism"][:70]
        md.append(f"| {r['reaction_id']} | {r['module']} | {r['type']} | {mech} | {r['validation_status']} |")
    md.append("")
    OUT_MD.write_text("\n".join(md))

    print(f"[inference_register] {n} weak SSc rows "
          f"(STRING-confirmed {n_string_ok}, STRING-not {n_string_no}, untested {n_untested})")
    print(f"[inference_register] {int(reg['lit_search_needed'].sum())}/{n} need a lit pass")
    print(f"[inference_register] wrote {OUT_TSV} + {OUT_MD}")


if __name__ == "__main__":
    main()
