#!/usr/bin/env python3
"""Prepare for a tagged release on GitHub + Zenodo.

Runs the v1.0 readiness gate:

  1. Working tree clean (no uncommitted changes)
  2. Branch is `main`
  3. CITATION.cff and .zenodo.json have no REPLACE_ME placeholders
  4. `make preflight` returns 0 (delegates)
  5. CHANGELOG.md is up-to-date with the upcoming tag (regenerated from
     git log on each run)

Prints the recommended `git tag` command at the end.

By default the script is non-destructive: it generates / overwrites
CHANGELOG.md but does NOT tag or push. Pass --tag VERSION to actually
create the tag.

Usage:
  scripts/release_prep.py                       # check + write CHANGELOG
  scripts/release_prep.py --tag v1.0            # also create the tag
  scripts/release_prep.py --tag v1.0 --push     # also push the tag

The Zenodo↔GitHub webhook mints a DOI within 1–2 minutes of the tag
being pushed (assuming the integration is enabled on zenodo.org).
"""
from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def run(cmd: list[str], check: bool = True, **kw) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=check, capture_output=True, text=True, **kw)


def check_clean_tree() -> bool:
    r = run(["git", "status", "--porcelain"], check=False)
    if r.stdout.strip():
        print(f"  [fail] working tree dirty:\n{r.stdout}")
        return False
    print("  [ ok ] working tree clean")
    return True


def check_branch() -> bool:
    r = run(["git", "rev-parse", "--abbrev-ref", "HEAD"], check=False)
    branch = r.stdout.strip()
    if branch != "main":
        print(f"  [fail] on branch '{branch}', expected 'main'")
        return False
    print(f"  [ ok ] branch = main")
    return True


def check_no_placeholders() -> bool:
    files = [Path("CITATION.cff"), Path(".zenodo.json")]
    ok = True
    for p in files:
        if not p.exists():
            print(f"  [fail] missing file: {p}")
            ok = False
            continue
        text = p.read_text(encoding="utf-8")
        n = text.count("REPLACE_ME") + text.count("0000-0000-0000-0000")
        if n:
            print(f"  [fail] {p}: {n} placeholder(s) (REPLACE_ME / 0000-…)")
            ok = False
        else:
            print(f"  [ ok ] {p}: no placeholders")
    return ok


def check_preflight() -> bool:
    r = run([sys.executable, "scripts/minerva_preflight.py"], check=False)
    if r.returncode != 0:
        print("  [fail] preflight reported blocking issues; rerun `make preflight`")
        print(r.stdout)
        return False
    print("  [ ok ] preflight passes (advisories may remain — see `make preflight`)")
    return True


def write_changelog(version: str) -> Path:
    """Regenerate CHANGELOG.md from `git log --oneline`."""
    r = run(["git", "log", "--oneline", "--reverse"], check=False)
    commits = [ln for ln in r.stdout.splitlines() if ln.strip()]

    lines = [
        f"# Changelog",
        "",
        f"This file is auto-generated by `scripts/release_prep.py` on every release prep.",
        "",
    ]
    if version:
        lines.append(f"## {version} — {__import__('datetime').date.today().isoformat()}")
        lines.append("")
    else:
        lines.append("## Unreleased")
        lines.append("")
    for c in commits:
        sha, _, msg = c.partition(" ")
        lines.append(f"- `{sha}` {msg}")
    lines.append("")
    out = Path("CHANGELOG.md")
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--tag", default="", help="if set, also create this git tag (e.g. v1.0)")
    ap.add_argument("--push", action="store_true", help="also push the new tag")
    ap.add_argument("--skip-preflight", action="store_true")
    args = ap.parse_args(argv[1:])

    print("=" * 72)
    print("Release readiness check")
    print("=" * 72)

    blocking_ok = True
    blocking_ok &= check_branch()
    blocking_ok &= check_clean_tree()
    blocking_ok &= check_no_placeholders()
    if not args.skip_preflight:
        blocking_ok &= check_preflight()

    cl = write_changelog(args.tag)
    print(f"  [info] CHANGELOG -> {cl}")

    if not blocking_ok:
        print()
        print("Blocking issues — release not ready. Fix the [fail] lines above.")
        return 1

    print()
    print("=" * 72)
    if args.tag:
        print(f"Tagging {args.tag} …")
        run(["git", "add", str(cl)], check=False)
        # Only commit if the changelog changed
        r = run(["git", "diff", "--cached", "--quiet"], check=False)
        if r.returncode != 0:
            run(["git", "commit", "-m", f"chore(release): refresh CHANGELOG for {args.tag}"], check=False)
            print(f"  [ ok ] committed CHANGELOG update")
        run(["git", "tag", "-a", args.tag, "-m", f"SSc-MIM release {args.tag}"], check=False)
        print(f"  [ ok ] created tag {args.tag}")
        if args.push:
            run(["git", "push", "origin", "main"], check=False)
            run(["git", "push", "origin", args.tag], check=False)
            print(f"  [ ok ] pushed main and tag to origin")
            print()
            print("Zenodo webhook will mint a DOI within ~1–2 minutes if the integration is enabled.")
        else:
            print()
            print("Tag created locally. To publish + trigger the Zenodo DOI:")
            print(f"  git push origin main && git push origin {args.tag}")
    else:
        print("All blocking checks green. To cut the release:")
        print(f"  scripts/release_prep.py --tag v1.0 --push")
        print("Or manually:")
        print(f"  git tag -a v1.0 -m 'SSc-MIM release v1.0'")
        print(f"  git push origin main && git push origin v1.0")

    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
